name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, bcmath, curl
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: none

    - name: Install PHP dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install npm dependencies and build assets
      run: |
        npm install
        npm run build
        ls -la public/build  # Перевіряємо, чи створена папка build

    - name: Set APP_KEY
      run: |
        echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env

    - name: Set up SQLite database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Create fake Vite manifest for testing
      run: |
        if [ ! -f public/build/manifest.json ]; then
          mkdir -p public/build
          echo '{}' > public/build/manifest.json
        fi

    - name: Run tests
      run: php artisan test
